<?php

namespace AppBundle\Repository;

/**
 * BookmarkedOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkedOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
